-- Estrutura para instalações novas. Bancos existentes exigem baseline explícito após inventário.
create table antiquebra (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table auditoria (id integer not null auto_increment, registro_id integer not null, usuario_id integer not null, data_acao datetime(6) not null, acao varchar(255) not null, tabela_afetada varchar(255) not null, primary key (id)) engine=InnoDB;
create table camelback (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table carcaca (id integer not null auto_increment, medida_id integer, modelo_id integer, pais_id integer, status_carcaca_id integer, usuario_id integer, dt_create datetime(6), dt_update datetime(6), uuid binary(16), dados varchar(255), dot varchar(255), fotos varchar(255), leitura_metadados varchar(255), numero_etiqueta varchar(255), status varchar(255), primary key (id)) engine=InnoDB;
create table carcaca_rejeitada (id integer not null auto_increment, medida_id integer, modelo_id integer, pais_id integer, dt_create datetime(6), dt_update datetime(6), uuid binary(16), descricao varchar(255), motivo varchar(255), primary key (id)) engine=InnoDB;
create table cobertura (cola_id integer not null, id integer not null auto_increment, usuario_id integer not null, dt_create datetime(6), dt_update datetime(6), fotos json, primary key (id)) engine=InnoDB;
create table cola (id integer not null auto_increment, producao_id integer not null, usuario_id integer, data_inicio datetime(6) not null, status enum ('Aguardando','Pronto','Vencido') not null, primary key (id)) engine=InnoDB;
create table controle_qualidade (id integer not null auto_increment, producao_id integer, tipo_observacao_id integer, usuario_id integer, dt_create datetime(6), fotos varchar(255), observacao varchar(255), primary key (id)) engine=InnoDB;
create table espessuramento (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table maquina_configuracao (id integer not null auto_increment, maquina_id integer not null, matriz_id integer not null, usuario_id integer not null, dt_create datetime(6) not null, dt_delete datetime(6), dt_update datetime(6), celular_id varchar(100) not null, descricao varchar(150), atributos JSON, primary key (id)) engine=InnoDB;
create table maquina_registro (id integer not null auto_increment, dt_create datetime(6) not null, dt_delete datetime(6), dt_update datetime(6), nome varchar(100) not null, numero_serie varchar(100), descricao varchar(250), status enum ('Ativa','Inativa','Manutencao') not null, primary key (id)) engine=InnoDB;
create table marca (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table matriz (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table medida (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table modelo (id integer not null auto_increment, marca_id integer, descricao varchar(255), primary key (id)) engine=InnoDB;
create table motorista (ativo bit not null, id integer not null auto_increment, usuario_id integer not null, data_atualizacao datetime(6), data_criacao datetime(6), cpf varchar(11) not null, observacoes varchar(1024), nome varchar(255) not null, placa_veiculo varchar(255), telefone varchar(255), primary key (id)) engine=InnoDB;
create table pais (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table perfil (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table pneus_vulcanizados (id integer not null auto_increment, producao_id integer not null, usuario_id integer not null, dt_create datetime(6) not null, dt_delete datetime(6), dt_update datetime(6), status enum ('FINALIZADO','INICIADO') not null, primary key (id)) engine=InnoDB;
create table producao (carcaca_id integer, id integer not null auto_increment, medida_pneu_raspado float(53), regra_id integer, usuario_id integer, dt_create datetime(6), dt_update datetime(6), uuid binary(16), dados varchar(255), fotos varchar(255), primary key (id)) engine=InnoDB;
create table regra (antiquebra1_id integer, antiquebra2_id integer, antiquebra3_id integer, camelback_id integer, espessuramento_id integer, id integer not null auto_increment, matriz_id integer, medida_id integer, modelo_id integer, pais_id integer, tamanho_max float(53), tamanho_min float(53), dt_create datetime(6), dt_delete datetime(6), dt_update datetime(6), tempo varchar(255), status enum ('EM_VALIDACAO','VALIDADA'), primary key (id)) engine=InnoDB;
create table rele (id integer not null auto_increment, maquina_registro_id integer not null, dt_create datetime(6) not null, dt_delete datetime(6), dt_update datetime(6), celular_id varchar(100) not null, ip varchar(255) not null, primary key (id)) engine=InnoDB;
create table status_carcaca (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table tipo_classificacao (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table tipo_observacao (id integer not null auto_increment, tipo_classificacao_id integer, descricao varchar(255), primary key (id)) engine=InnoDB;
create table tipo_valida_regra (id integer not null auto_increment, descricao varchar(255), primary key (id)) engine=InnoDB;
create table usuario (id integer not null auto_increment, login varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_perfil (perfil_id integer not null, usuario_id integer not null) engine=InnoDB;
create table valida_regra (id integer not null auto_increment, qualidade_id integer, regra_id integer, status bit, tipo_valida_regra_id integer, dados varchar(255), primary key (id)) engine=InnoDB;
alter table carcaca add constraint UKjthvfnlpnwi2177vbcwjlrjja unique (numero_etiqueta);
alter table maquina_registro add constraint UKs4ma428lpp21oy4y8c11p43pt unique (numero_serie);
alter table motorista add constraint UKm3qo604s7ko66puhowap8mohy unique (usuario_id);
alter table motorista add constraint UKrbjk7fv6x6kadmtchy9pb5bt3 unique (cpf);
alter table rele add constraint UK8juy58eud5mns037hl6f9rr7m unique (ip);
alter table usuario add constraint UKpm3f4m4fqv89oeeeac4tbe2f4 unique (login);
alter table auditoria add constraint FK4ckabg4x8ns3xh5i1l6eam139 foreign key (usuario_id) references usuario (id);
alter table carcaca add constraint FKoxhgdwhce0onq6pdchu44yu3r foreign key (usuario_id) references usuario (id);
alter table carcaca add constraint FKaxc1y4ihqn5h49rr233tiv7tt foreign key (medida_id) references medida (id);
alter table carcaca add constraint FKma7mijkw7a3bpo3n4bg60u8mv foreign key (modelo_id) references modelo (id);
alter table carcaca add constraint FK2244m3igin7ng72k1m70tyn66 foreign key (pais_id) references pais (id);
alter table carcaca add constraint FKdxrhbl47hl3ji6pflwvg3i6x3 foreign key (status_carcaca_id) references status_carcaca (id);
alter table carcaca_rejeitada add constraint FK73mmfg2exmrx82puh5hoclge1 foreign key (medida_id) references medida (id);
alter table carcaca_rejeitada add constraint FKacs4lwmix7374y367i0ihr1t4 foreign key (modelo_id) references modelo (id);
alter table carcaca_rejeitada add constraint FKay7lcmialgn755hc5674rc7j5 foreign key (pais_id) references pais (id);
alter table cobertura add constraint FKc5rmc9n1wmf3rr3c8hdd2dmhc foreign key (cola_id) references cola (id);
alter table cobertura add constraint FKgo6vaas2dt27ma4vigbx6nrke foreign key (usuario_id) references usuario (id);
alter table cola add constraint FKf30p3ag0jbh4oop9x96hj4y68 foreign key (producao_id) references producao (id);
alter table cola add constraint FKtnb974hsaa2vm65guew6dpffk foreign key (usuario_id) references usuario (id);
alter table controle_qualidade add constraint FK32sbjc359i4t65cc2psesbk91 foreign key (producao_id) references producao (id);
alter table controle_qualidade add constraint FK1divmcbnktv0vjw4sxob7u1f6 foreign key (tipo_observacao_id) references tipo_observacao (id);
alter table controle_qualidade add constraint FK44im9wp9xgrio521fd0ucl09g foreign key (usuario_id) references usuario (id);
alter table maquina_configuracao add constraint FKqg2omb2o1e1spgu1xixlmkhhs foreign key (maquina_id) references maquina_registro (id);
alter table maquina_configuracao add constraint FK4hgj8hx2bdr45706vwt1v4vve foreign key (matriz_id) references matriz (id);
alter table modelo add constraint FKllxq2dldvhxvb5q9csar7vdfy foreign key (marca_id) references marca (id);
alter table motorista add constraint FKjpl954mh4vubwwed4m0gl55gn foreign key (usuario_id) references usuario (id);
alter table pneus_vulcanizados add constraint FKkic2yrfsf4tv2y7iypuw7xfsp foreign key (producao_id) references producao (id);
alter table pneus_vulcanizados add constraint FKowpkr9vx27ub4steefx8af9v2 foreign key (usuario_id) references usuario (id);
alter table producao add constraint FKgx9p0o6ilirftv5pjhm8uvqe3 foreign key (carcaca_id) references carcaca (id);
alter table producao add constraint FKfcuetqkerwhg2lp6na001tw7i foreign key (usuario_id) references usuario (id);
alter table producao add constraint FK2u3uwf3cauga0agx2sbnwodut foreign key (regra_id) references regra (id);
alter table regra add constraint FK66laomgvctepp0pxota0ocskg foreign key (antiquebra1_id) references antiquebra (id);
alter table regra add constraint FKai5f7vib668t8h3dy17aefd5t foreign key (antiquebra2_id) references antiquebra (id);
alter table regra add constraint FKdnk7pungklvrlvc0lwl1e59c1 foreign key (antiquebra3_id) references antiquebra (id);
alter table regra add constraint FKgmanphdkr2iv3b3e3et9u582l foreign key (camelback_id) references camelback (id);
alter table regra add constraint FK6sd2trwb81xgqyiwnap8ebp8g foreign key (espessuramento_id) references espessuramento (id);
alter table regra add constraint FK8pwueox2et4qa0aexuhbrhcv7 foreign key (matriz_id) references matriz (id);
alter table regra add constraint FK1p2poyrv7qf7sy2ne8y9v9ogc foreign key (medida_id) references medida (id);
alter table regra add constraint FKh5yhjb834k7yv91nv1gkfhgpu foreign key (modelo_id) references modelo (id);
alter table regra add constraint FKpgl4xhssb74jmsq6wyxu3r7w7 foreign key (pais_id) references pais (id);
alter table rele add constraint FKj9xaqqh8egsgvd7rnd2dthyac foreign key (maquina_registro_id) references maquina_registro (id);
alter table tipo_observacao add constraint FKhfg9dho0d12phh5h59bcerk2h foreign key (tipo_classificacao_id) references tipo_classificacao (id);
alter table usuario_perfil add constraint FK22cgfn0obntlvqyfn33pyk24d foreign key (perfil_id) references perfil (id);
alter table usuario_perfil add constraint FKnrjqnbylalt4ykxbcef24f57w foreign key (usuario_id) references usuario (id);
alter table valida_regra add constraint FK4hflho3eiq4tpsfudl6fku0fy foreign key (qualidade_id) references controle_qualidade (id);
alter table valida_regra add constraint FKgvqilhcd5705umlsk29bu2rl6 foreign key (regra_id) references regra (id);
alter table valida_regra add constraint FKlrl8o4x3hksl47utc8ftdcah6 foreign key (tipo_valida_regra_id) references tipo_valida_regra (id);
